version: 0.0
os: linux
files:
  - source: /ec2-app/fsx-analyzer
    destination: /var/www/html/fsx-analyzer
    file_exists_behavior: OVERWRITE
  - source: /scripts
    destination: /opt/deployment/scripts
    file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/html/fsx-analyzer
    pattern: "**"
    owner: nginx
    group: nginx
    mode: 755
    type:
      - file
      - directory
  - object: /opt/deployment/scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: /scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /scripts/start_services.sh    
      timeout: 300
      runas: root
