version: 0.0
os: linux
files:
  - source: /artifacts/ec2-app/nginx/conf.d
    destination: /etc/nginx/conf.d
  - source: /artifacts/ec2-app/fsx-analyzer
    destination: /var/www/html/fsx-analyzer
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_services.sh
      timeout: 300
      runas: root
