version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Checking which components changed"
      - LAMBDA_CHANGED="true"
      - EC2_CHANGED="true"
      - echo "Lambda changed is $LAMBDA_CHANGED"
      - echo "EC2 changed is $EC2_CHANGED"
  
  build:
    commands:
      - echo "Building components"
      - echo "Lambda changed is $LAMBDA_CHANGED"
      - echo "EC2 changed is $EC2_CHANGED"
  
  post_build:
    commands:
      - echo "Creating deployment artifacts"
      - mkdir -p artifacts/lambda
      - mkdir -p artifacts/ec2-app/fsx-analyzer
      - mkdir -p artifacts/ec2-app/nginx/conf.d
      - mkdir -p artifacts/scripts
      
      # Copy Lambda files
      - cp -r lambda/src/* artifacts/lambda/ || echo "No Lambda files to copy"
      
      # Copy EC2 files
      - cp -r ec2-app/fsx-analyzer/* artifacts/ec2-app/fsx-analyzer/ || echo "No fsx-analyzer files to copy"
      - cp -r ec2-app/nginx/conf.d/* artifacts/ec2-app/nginx/conf.d/ || echo "No nginx files to copy"
      
      # Create deployment scripts
      - echo "#!/bin/bash" > artifacts/scripts/before_install.sh
      - echo "set -e" >> artifacts/scripts/before_install.sh
      - echo "echo \"Starting before_install.sh at \$(date)\"" >> artifacts/scripts/before_install.sh
      - echo "rm -f /var/www/html/fsx-analyzer/analyze_fsx.php" >> artifacts/scripts/before_install.sh
      - echo "mkdir -p /var/www/html/fsx-analyzer" >> artifacts/scripts/before_install.sh
      - echo "mkdir -p /etc/nginx/conf.d" >> artifacts/scripts/before_install.sh
      - echo "systemctl stop nginx || echo \"Failed to stop nginx, continuing anyway\"" >> artifacts/scripts/before_install.sh
      - echo "echo \"before_install.sh completed at \$(date)\"" >> artifacts/scripts/before_install.sh
      
      - echo "#!/bin/bash" > artifacts/scripts/after_install.sh
      - echo "set -e" >> artifacts/scripts/after_install.sh
      - echo "echo \"Starting after_install.sh at \$(date)\"" >> artifacts/scripts/after_install.sh
      - echo "chmod -R 755 /var/www/html/fsx-analyzer" >> artifacts/scripts/after_install.sh
      - echo "chown -R nginx:nginx /var/www/html/fsx-analyzer" >> artifacts/scripts/after_install.sh
      - echo "echo \"after_install.sh completed at \$(date)\"" >> artifacts/scripts/after_install.sh
      
      - echo "#!/bin/bash" > artifacts/scripts/start_services.sh
      - echo "set -e" >> artifacts/scripts/start_services.sh
      - echo "echo \"Starting start_services.sh at \$(date)\"" >> artifacts/scripts/start_services.sh
      - echo "systemctl restart nginx" >> artifacts/scripts/start_services.sh
      - echo "echo \"start_services.sh completed at \$(date)\"" >> artifacts/scripts/start_services.sh
      
      # Make scripts executable
      - chmod +x artifacts/scripts/before_install.sh
      - chmod +x artifacts/scripts/after_install.sh
      - chmod +x artifacts/scripts/start_services.sh
      
      # List files for verification
      - echo "Listing artifact contents:"
      - ls -la artifacts/
      - ls -la artifacts/scripts/

artifacts:
  files:
    - appspec.yml
    - artifacts/**/*
  discard-paths: no
