version: 0.2

env:
  variables:
    DEPLOY_TARGET: "none"

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo "Detecting changes to determine deployment target..."
      - >
        if git diff --name-only HEAD~1 HEAD | grep -E '^ec2-app/|^nginx/|^appspec.yml|^index.html'; then
          echo "Detected EC2 changes"; export DEPLOY_TARGET="ec2";
        elif git diff --name-only HEAD~1 HEAD | grep -E '^lambda/'; then
          echo "Detected Lambda changes"; export DEPLOY_TARGET="lambda";
        else
          echo "No deployable changes detected"; export DEPLOY_TARGET="none";
        fi
      - echo "DEPLOY_TARGET=${DEPLOY_TARGET}" > build-target.txt
      - cat build-target.txt

  build:
    commands:
      - echo "Building project for target: ${DEPLOY_TARGET}"

  post_build:
    commands:
      - |
        if [ "$DEPLOY_TARGET" = "ec2" ]; then
          echo "Triggering EC2 sub-pipeline"
        elif [ "$DEPLOY_TARGET" = "lambda" ]; then
          echo "Triggering Lambda sub-pipeline"
        else
          echo "No deploy target — skipping"
        fi
