version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y || true

  pre_build:
    commands:
      - echo "Preparing build environment..."

  build:
    commands:
      - echo "Building EC2 artifact..."
      - mkdir -p artifacts/ec2-app/fsx-analyzer
      - cp -r ec2-app/fsx-analyzer/* artifacts/ec2-app/fsx-analyzer/
      - mkdir -p artifacts/scripts
      - cp scripts/*.sh artifacts/scripts/
      - cp appspec.yml artifacts/
      - echo "Build complete."

  post_build:
    commands:
      - echo "Zipping artifacts..."
      - cd artifacts
      - zip -r ../deploy-package.zip .
      - cd ..
      - echo "Post-build complete."
