version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Checking which components changed"
      - LAMBDA_CHANGED="true"
      - EC2_CHANGED="true"
      - echo "Lambda changed is $LAMBDA_CHANGED"
      - echo "EC2 changed is $EC2_CHANGED"
  
  build:
    commands:
      - echo "Building components"
      - echo "Lambda changed is $LAMBDA_CHANGED"
      - echo "EC2 changed is $EC2_CHANGED"
  
  post_build:
    commands:
      - echo "Creating deployment artifacts"
      - mkdir -p artifacts/ec2-app/fsx-analyzer
      - mkdir -p artifacts/scripts
    
      # Copy files with verbose output
      - echo "Copying EC2 files..."
      - cp -rv ec2-app/fsx-analyzer/* artifacts/ec2-app/fsx-analyzer/ || echo "No fsx-analyzer files to copy"
      - ls -la artifacts/ec2-app/fsx-analyzer/
    
      # Create scripts
      - echo "Creating deployment scripts..."
      # (your script creation commands)


artifacts:
  files:
    - appspec.yml
    - artifacts/**/*
    - lambda-deploy.sh
    - lambda-buildspec.yml
  discard-paths: no
