post_build:
  commands:
    - echo "Creating deployment artifacts"
    - mkdir -p artifacts/lambda
    - mkdir -p artifacts/ec2-app/fsx-analyzer
    # Deliberately NOT creating artifacts/ec2-app/nginx/conf.d
    - mkdir -p artifacts/scripts
    
    # Copy Lambda files
    - cp -r lambda/src/* artifacts/lambda/ || echo "No Lambda files to copy"
    
    # Copy ONLY fsx-analyzer files, NOT nginx config
    - cp -r ec2-app/fsx-analyzer/* artifacts/ec2-app/fsx-analyzer/ || echo "No fsx-analyzer files to copy"
    
    # Create deployment scripts
    # [script creation commands as before]
