version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Checking which components changed"
      - echo "Current commit is $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - LAMBDA_CHANGED="false"
      - EC2_CHANGED="false"
      - echo "Setting Lambda changed to $LAMBDA_CHANGED"
      - echo "Setting EC2 changed to $EC2_CHANGED"
  
  build:
    commands:
      - echo "Building components"
      - echo "Lambda changed is $LAMBDA_CHANGED"
      - echo "EC2 changed is $EC2_CHANGED"
  
  post_build:
    commands:
      - echo "Creating deployment artifacts"
      - mkdir -p artifacts
      - echo "Deployment preparation complete"

artifacts:
  files:
    - artifacts/**/*
    - appspec.yml
    - lambda-deploy.sh
    - lambda-buildspec.yml
  discard-paths: no
