version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo Installing dependencies...
      - mkdir -p build/package
      - pip install -r requirements.txt -t build/package || echo "No requirements.txt found, skipping."
      - mkdir -p build/package/src
      - cp lambda/src/main.py build/package/src/
      - touch build/package/src/__init__.py  # Create empty __init__.py file to make src a proper package
  build:
    commands:
      - echo Zipping deployment package...
      - cd build/package
      - zip -r9 ../lambda_package.zip .

artifacts:
  files:
    - build/lambda_package.zip
