version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t build/ || echo "No requirements.txt, skipping..."
  pre_build:
    commands:
      - echo Preparing Lambda package...
      - mkdir -p build/package
      - cp src/main.py build/package/
  build:
    commands:
      - echo Packaging Lambda zip...
      - cd build/package
      - zip -r9 ../../lambda_package.zip .
artifacts:
  files:
    - build/lambda_package.zip
