version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo Installing dependencies...
      - mkdir -p build
      - pip install -r requirements.txt -t build || echo "No requirements.txt found, skipping."
      
  build:
    commands:
      - echo "Creating deployment package..."
      - cp lambda/src/main.py build/  # Copy main.py to the root of build
      - cd build
      - zip -r9 ../lambda_package.zip .

artifacts:
  files:
    - lambda_package.zip
