version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo Installing dependencies...
      - mkdir -p build
      - pip install -r requirements.txt -t build || echo "No requirements.txt found, skipping."
      
  build:
    commands:
      - echo "Creating deployment package..."
      - cp lambda/src/main.py build/  # Copy main.py directly to the root of build directory
      - cd build
      - ls -la  # Verify files are in the right place
      - zip -r9 ../lambda_package.zip .  # Create zip with contents of build directory

artifacts:
  files:
    - lambda_package.zip
